public class Address {
    public void homeAddress() {
    string yourName = 'Bega';
    integer totalNumberOfMembersInYourFamily = 4;
    string houseName = 'TKM';
    string houseNumber = '6';
    string streetName = 'Ashgabat';
    string cityName = 'Bayramali';
    string stateName = 'Mary';
    string iSOcode = 'TKM';
    string countryName = 'Turkmenistan';
    string isoStateCode = 'MR';
    integer zipCode = 746000;
    boolean isYourCurrentHome = False;

    system.debug('yourName= ' + yourName);
    system.debug('totalNumberOfMembersInYourFamily= ' +  totalNumberOfMembersInYourFamily);
    system.debug('houseNumber= '+ houseNumber);
    system.debug('houseName= '+ houseName);
    system.debug('streetName= '+ streetName);
    system.debug('cityName= ' + cityName);
    system.debug('stateName= ' + stateName);
    system.debug('iSOcode= ' + iSOcode);
    system.debug('countryName= ' + countryName);
    system.debug('isoStateCode= ' + isoStateCode);
    system.debug('zipCode= ' + zipCode);
    system.debug('isYourCurrentHome= ' + isYourCurrentHome);

    }
}
