LoopsDemo ld = new LoopsDemo();
ld.print_int_while();


loopsDemo ld1 = new loopsDemo();
ld1.print_N_numbers(55);


loopsDemo ld2 = new loopsDemo();
ld2.print_N_Odd_numbers(4,94);

loopsDemo ld3 = new loopsDemo();
string day1 = ld3.getDayFromNumber(1);
system.debug('day 1 is = ' + day1);
string day2 = ld3.getDayFromNumber(2);
system.debug('day 2 is = ' + day2);
string day10 = ld3.getDayFromNumber(10);
system.debug('day 10 is = ' + day10);